<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IER1J9F" failures="1" tests="8" name="Default test" time="33.445" errors="0" timestamp="2022-09-14T11:05:00 WIB">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="2.556">
    <failure type="java.lang.AssertionError" message="expected [https://sqa.peluangkerjaku.com/tele/] but found [https://google.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://sqa.peluangkerjaku.com/tele/] but found [https://google.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.juaracoding.telemarketing.step_definitions.TestLogin.user_go_to_invalid_web_telemarketing(TestLogin.java:34)
at âœ½.User go to invalid Web Telemarketing(file:///C:/Users/HP.DESKTOP-IER1J9F/eclipse-workspace/git-telemarketing/src/test/resources/features/1.Login.feature:4)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.946"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.421"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.683"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="7.028"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="4.073"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="3.23"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="3.888"/>
</testsuite> <!-- Default test -->
